#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $APP_DATABASE_USER WITH PASSWORD '$APP_DATABASE_PASSWORD';
	CREATE DATABASE app_db TEMPLATE template0 ENCODING 'utf8' LOCALE 'en_US.utf8';
	ALTER DATABASE app_db OWNER TO $APP_DATABASE_USER;
	GRANT ALL PRIVILEGES ON DATABASE app_db TO $APP_DATABASE_USER;
EOSQL
