= Actuators
:toc:

== Configuration
Actuator endpoints must be enabled in `application.properties` exposing only necessary endpoints.

[source,properties]
----
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=info,metrics,health
----

In addition, every endpoint should be enabled individually (See sections below for more details)

Enabled endpoints can be accessed through `/actuator` by default. This can be changed using the `base-path` configuration
in `application.properties`:

[source,properties]
----
management.endpoints.web.base-path: /public/actuator
----

== Endpoints

=== Info

This endpoint allows display information about the application through `/actuator/info` endpoint including
build information generated by `spring-boot-maven-plugin` Maven plugin and random information included in `application.properties`.

First of all, we need to enable the endpoint in `application.properties`

[source,properties]
----
management.endpoint.info.enabled=true
----

To provide build information is necessary to configure `spring-boot-maven-plugin` executing the `build-info` goal.

[source,xml]
----
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <!-- . . . -->
    <executions>
        <execution>
            <id>build-info</id>
            <goals>
                <goal>build-info</goal>
            </goals>
        </execution>
        <!-- . . . -->
    </executions>
</plugin>
----

This will generate `build-info.properties` file inside `/target/META-INF` folder with this info. E.G.

[source,properties]
----
build.artifact=springboot-showcase-main
build.group=com.bitsmi.springboot-showcase
build.name=springboot-showcase-main
build.time=2024-03-16T08\:32\:12.088Z
build.version=2.0.0-SNAPSHOT
----

Custom information can be added in `application.properties` enabling `management.info.env.enabled` property
and specifying them using `info` prefix. If properties file is filtered by Maven, we can use Maven env variables
like `project.name`, `project.version`, etc. to make this configuration more general.

[source,properties]
----
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=${project.description}
info.app.version=${project.version}
----

We can use an infix to categorize the properties (`app` in the example above), so that endpoint's response will contain inner json objects
according to them.

After doing these configurations, `/actuator/info` will provide us with a response like this:

[source,json]
----
{
  "app": {
    "name": "springboot-showcase-main",
    "description": "SpringBoot Showcase Main",
    "version": "1.0.0-SNAPSHOT"
  },
  "build": {
    "artifact": "springboot-showcase-main",
    "name": "springboot-showcase-main",
    "time": "2024-03-16T08:32:12.088Z",
    "version": "2.0.0-SNAPSHOT",
    "group": "com.bitsmi.springboot-showcase"
  }
}
----

=== Health
TODO

- `/actuator/health`

=== Metrics
TODO

- `/actuator/metrics`
- `/actuator/metrics/userApiController`
- `/actuator/metrics/userApiController?tag=error%3AIllegalStateException`

=== Custom actuators
TODO

== References
- https://docs.spring.io/spring-boot/docs/3.2.x/actuator-api/htmlsingle/#overview
