= Architecture

== Modules

Application's modules have the following dependency diagram:

[plantuml]
----
@startuml
rectangle main
rectangle " " as setup {
    rectangle application
    rectangle infrastructure
    rectangle domain
    rectangle web
}

main .right.> setup : "assembles"
web --> application
web --> infrastructure : "optional"
application --> domain
infrastructure --> domain
@enduml
----

[id=_main_module_description]
=== Main
**Purpose**

`Main` module serves as entry point for application.
It configures which modules are assembled to build the application.
This is done in `MainModuleConfig` class through `@Import` statements of the corresponding modules that will form part of the application

E.G.

[source,java]
----
@Configuration
@Import({
        WebModuleConfig.class,
        ApplicationModuleConfig.class,
        InfrastructureModuleConfig.class
})
public class MainModuleConfig
{

}

----

**Responsibilities**

* Configure application assembly
* Define Docker & Docker compose configurations related to application's deployment

=== Application
**Purpose**

`Application` module is where application's use cases are implemented. This module depends on `Domain` module that provides
components implementing the required business logic for the use cases.

`Application` module is also responsible for manage transactionality and event publication.
Every endpoint module such as `web`, `messaging`, etc. should depend on this module where they can found the implementations of required use cases.

**Responsibilities**

* Implement application use cases. This layer should not implement business logic related to domain. It should delegate it to `Domain` module components
* Implement top level transactionality when needed
* Publish related internal / external events

**Key components**
* `ApplicationCommand` and `ApplicationQuery` components that implement a specific use case.
`ApplicationCommands` will implement actions that modify application state / data
and `ApplicationQuery` will be used for data retrieval
E.G. `UserCreationApplicationCommand` will implement the use case `create an user`

=== Infrastructure
**Purpose**

`Infrastructure` module contains all infrastructure related configurations

**Responsibilities**

* Implement persistence support (JPA, Mongo...)
* Configure transversal services like Caches, Observability...
Each of this configurations should be made in a separate configuration so dependant modules can import them to used in, for example, integration tests
* Configuration of `Domain` module's related managed beans E.G. make `Domain Services` available to be injected in `Application Services`
* Attach `Domain Service` interfaces to corresponding `Infrastructure` implementation. E.G. `Repository Services`

**Key components**
* `Config` to configure related traversal infrastructure features like persistence, observability, validation, etc.
* `Entity` classes. E.G. `UserEntity`
* `Repository` classes that manage entities. These classes are not exposed to outside
* `DomainRepository` classes. Wrap raw `Repository` classes and are also in charge of transform `entities` to `model` classes
* `ModelMapper` classes in charge of `entity` to `model` transformation done in `DomainRepository`s

=== Domain
**Purpose**

`Domain` module implements applications business logic in an agnostic way, trying to not be dependant of frameworks

**Responsibilities**

* Implement model classes
* Implement domain business logic in `DomainService`s (Queries & Commands)
* Implement validators & model object factories
* Define interfaces that will be implemented in `Infrastructure` module for infrastructure dependant components like persistence or event publishing

**Key components**
* `DomainCommandService` and `DomainQueryService` implements business logic for actions and data retrieval
* `DomainFactory` classes that implement the creation of domain model objects. E.G. `UserDomainFactory`
* `DomainRepository` interfaces that should be implemented in `Infrastrcture` module.
These interfaces are part of the public interface of the module and can be used in `Application module`

=== Web
**Purpose**

`Web module` is a mix between `Infrastructure` and `Application` modules
as it's in charge of configure web infrastructure components like web security and implement controllers
that are the entry points to execute use cases.

**Responsibilities**

* Spring web configurations
* Spring rest based controllers definition
* Spring security configuration, including basic & JWT auth

**Key components**
* `Controller` classes
* `Config` classes for infrastructure features. E.G. `WebSecurityConfig`

== Module general structure

=== Packages

The general package structure and naming is defined by the following guide:

[plantuml]
----
@startuml
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
}
legend

<:package:> module
|_ <:file_folder:> src/main/java/<module package name>
  |_ <:file_folder:> config
    |_ <:page_facing_up:> Module Config
    |_ <:page_facing_up:> Feature Config 1
    |_ <:page_facing_up:> Feature Config 2
    |_ . . .
  |_ <:file_folder:> event
    |_ <:file_folder:> listener
      |_ <:page_facing_up:> Event Listener
    |_ <:page_facing_up:> Event Definition
  |_ <:file_folder:> <context>
    |_ <:file_folder:> config
    |_ <:file_folder:> event
    |_ <:file_folder:> impl
      |_ <:page_facing_up:> Service Impl
    |_ <:page_facing_up:>Exposed Service Interface
  |_ <:page_facing_up:> Module Package Marker Interface

end legend
@end uml
----

* **Config**: Contains the **Main Config** for the module that will be the entry point for the component scan
and other module's dependencies definition using Spring's `@Import` statements. This package will also contain
additional feature enable configurations such as **Web MVC**, **Web Security**, **Cache**, **Observability**, **AOP**, etc.
Every feature configuration will be located in it's related module if it's only used in / affecting it (E.G. **Web MVC** in **Web** module)
or in **Infrastructure** module if it's a global feature (E.G. **AOP**, **Observability**, **Caches**)
* **Event**: Contains general event definition and listeners. The main use case for these events is to be used
as entry point for an external general event, such as Spring's lifecycle events (E.G. **ApplicationStartedEvent**)
that can be used to trigger module general actions. Context specific event definitions / listeners must be defined in context related subpackage
* **Contexts**: A context should contain components related to a specific bounded context of the domain or concept in the application.
Every context can define its **Exposed service interfaces** at the root of the module.
Implementations for own **Service interfaces** will be placed in `impl` subpackage.
Also, a special context named **Common** can be defined as a place to put shared components that can be used by other contexts and doesn't have
enough meaning to put then in its own context. **Common** context will not contain general configs or event listeners because they aren't dependencies of other contexts.
In that case, these components can be placed in top `config` and `event/listeners` packages of the module
because in that
* **Module Package Marker Interface**: Java interface intended to be used in Spring's component scans as type-safe alternative to basePackages for specifying the packages to scan for annotated components.

=== Configuration

Every module has its own `module config` class in charge of trigger the component scan on himself. It is also possible to filter components that doesn't have to be scanned automatically because they are optional and must be manually imported using an `@Import` annotation. The marker annotation `IgnoreOnComponentScan` can be used to do that. E.G.

```java
@Configuration
// This class will be ignored by automatic component scan
@IgnoreOnComponentScan
public class OptionalConfig {

}

//----------------------------------

@Configuration
@ComponentScan(
        basePackageClasses = { IWebPackage.class },
        excludeFilters = @ComponentScan.Filter(type = FilterType.ANNOTATION, classes = IgnoreOnComponentScan.class)
)
public class WebModuleConfig {

}
```

As explained in xref:_main_module_description[Main module]'s description section, all module configurations will be assembled in the `MainModuleConfig` class using `@Import` annotation.

=== Interactions

The modules presented in this document follow the `Onion Architecture` schema.
The execution flow goes from the outermost part of the "onion" to the inside, from left to right.

image::explanation/architecture/onion_architecture.drawio.svg[Interactions diagram,align="center"]

== Variations

=== Layered module

Instead of having separate modules for every module defined in this Architecture document,
they can be defined as a layered architecture in the same package. Every module can be transformed
in a subpackage.

[plantuml]
----
@startuml
skinparam Legend {
	BackgroundColor transparent
	BorderColor transparent
}
legend

<:package:> example-webservice
|_ <:file_folder:> src/main/java
  |_ <:file_folder:> com.example.example.webservice
    |_ <:file_folder:> main
      |_ <:file_folder:> config
      |_ <:page_facing_up:> MainProgram
    |_ <:file_folder:> web
      |_ <:file_folder:> config
      |_ <:file_folder:> controller
      |_ <:file_folder:> . . .
    |_ <:file_folder:> application
      |_ <:file_folder:> config
      |_ <:file_folder:> . . .
    |_ <:file_folder:> domain
      |_ <:file_folder:> . . .
    |_ <:file_folder:> infrastructure
      |_ <:file_folder:> config
      |_ <:file_folder:> . . .

end legend
@end uml
----

=== Split / merge modules

The same way that we can have a single layered module, we can also merge / split the modules
explained before.

**Examples of merge modules**:

- `Web module` can be integrated into `Infrastructure` and `Application`
modules, putting configurations in the first one and controllers in the second.
- Define the `Domain layer` in a separate module and put the others in a common module.
By this way, we can isolate domain business logic from framework dependant components.
- Merge `Application` and `Domain` layers in a `Core module` so that application's use cases
and business logic are isolated from input / output (E.G. web controllers and persistence)
