= Fluent REST API client

== Concept

This document introduces the design for a fluent API allowing executing different operations defined by a remote service.

Given a remote service API, we can define the following concepts:

* **Resource**: Full path to the resource. E.G. `/category/1`
* **(Sub)domain**: URL path that groups resources. E.G. The `/category/1` resource is defined under `/category` domain.
Also, we can define subdomains under a main domain. E.G.  we can have `/product` subdomain under `/category/{id}` domain (`/category/{id}/product`)
* **Operation**: Action to be done on the resource or (sub)domain, usually a CRUD operation. 

In order to illustrate the design, we introduce the following API that models a service to operate with categorized products:

* We have a remote service API that defines 2 main domains: `/info` and `/category`:
* `/info` domain defines the following operation:
	** `get version` doing a `GET` request to the `/info/version` endpoint
* `/category` domain defines the following operations:
	** `list` categories doing a `GET` request to the `/category` endpoint
	** get an specific category `detail` doing a `GET` request to the `/category/{id}` endpoint
	** `create` a new category doing a `POST` request to the `/category` endpoint
	** `update` an existent category doing a `PUT` request to the `/category/{id}` endpoint
	** `delete` an existent category doing a `DELETE` request to the `/category/{id}` endpoint
* `/category` domain defines the subdomain `/product` for each element on it
* `/category/product` subdomain defines the following operations:
	** `list` fields belonging to a product doing a `GET` request to the `/category/{category id}/product` endpoint
	
In a schematic way:

[plantuml]
----
@startwbs
* /
**[#lightblue] info
***[#lightgreen] getVersion
**[#lightblue] category
***[#lightgreen]< list
***[#lightgreen]< detail
***[#lightgreen]< create
***[#lightgreen]< update
***[#lightgreen]< delete
***[#lightblue] product
****[#lightgreen] list

legend left
|<back:#lightblue>     </back>| Domain |
|<back:#lightgreen>     </back>| Operation |
endlegend
@endwbs
----
	
With the previous concepts, we can define a series of client API elements to access them:

=== Client

Used as entrypoint to the client API providing access to implemented `API Builders` for service API domains.

Wraps the underlying client that will be used to consume the service API, providing also a builder to create and configure it. This client wrapper creates an independent layer that makes possible
to use different underlying clients (E.G. Spring's `RestClient`, `RestTemplate`, `OkHttp3`...)
maintaining the same API.

=== API Builders

`API Builders` provide methods to access and configure operations to be executed on the different domains or resources supported
by the `Client` using its top level API methods.

An `API Builder` should be usually created using domain related data and then select the operation that should be executed. 
If the operation does not define additional intermediate methods, the operation selection method can execute directly the operation,
returning the resulting data directly (if any). E.G.

[source,java]
----
// ElementApiBuilder.java
. . .
public SomeElement update(SomeElementInputData newData) {
	// Create update operation using required arguments and execute it directly
	return new UpdateOperation(. . .).update(newData);
}
. . .
----

We can define several kinds of `Api Builder` classes depending on its target type:

* `SetApiBuilder`: Meant to be used for operations over datasets (retrieval, batch update...).
The builder may or may not receive as input a filter / selector to limit the dataset affected.
* `CreationApiBuilder`: Meant to be used for element creation operations targeting a specific (sub)domain. The builder will receive
the data to send to the server as input.
* `ElementApiBuilder`: Meant to be used for individual element data retrieval or manipulation involving a unique identifier received as input

An `ApiBuilder` can also be used to group other `ApiBuilder`s, at top level or nested domain level.
In that case it will contain calls to other builders if it's needed to access to a grouped / nested domain builder or operation API.

=== Operations

`Operations` are the final operators of the API in charge of execute the final call to the remote service using de underlying configured client. 
They define a method in charge of executing the operation along others intermediate methods meant to add or modify the data
or behaviour of this execution. For example, a dataset retrieval operation may define intermediate methods like `paginate(...)` 
or `sort(...)` that configure the pagination parameters of the request.

== Example

Following the explanation above, we can model our client API as follows:

=== Client

Entrypoint of client API. Provides methods to give access to the `API Builders` that group operations by domain.

[source,java]
----
public class ServiceClient {
    // Underlying HTTP client instance
    private final RestClient restClient;

    private ServiceClient(RestClient restClient) {
        this.restClient = restClient;
    }

    public static Builder builder() {
        return new Builder();
    }

    /* API Builders accessors
     */
    public InfoApiBuilder infoApi() {
        return new InfoApiBuilder(restClient);
    }

    public CategoryApiBuilder categoryApi() {
        return new CategoryApiBuilder(restClient);
    }

    /* Builder allowing to configure the underlying client
     */
    public static class Builder {
        // . . .
    }
}
----

Once implemented, we can get an instance of our client as follows:

[source,java]
----
ServiceClient client = ServiceClient.builder()
		.withBaseUrl(remoteServiceUrl)
		.build();
----

=== Info API

`Info API Builder` provides access to every operation defined by the implemented domain. In this case it only have an operation, accessible through `serviceVersion()` method.

[source,java]
----
public class InfoApiBuilder {

    private final RestClient restClient;

    public InfoApiBuilder(RestClient restClient) {
        this.restClient = restClient;
    }

    public ServiceVersionOperation serviceVersion() {
        return new ServiceVersionOperation(restClient);
    }
}
----

This is a simple `Operation` that only allows retrieving data through `get()` method and does not provide additional methods to configure additional parameters

[source,java]
----
public class ServiceVersionOperation {
    private final RestClient restClient;

    ServiceVersionOperation(RestClient restClient) {
        this.restClient = restClient;
    }
    /* Method that executes the operation sending the request to the remote service
     */
    public String get() {
        return restClient.get()
                .uri("/api/info/version")
                .retrieve()
                .body(String.class);
    }
}
----

Usage example:

[source,java]
----
String actualServiceVersion = client.infoApi()
	.serviceVersion()
	.get();
----

=== Category API

`CategoryApiBuilder` example shows how to group nested `ApiBuilders` by domain.
It serves as an accessor to the specific `ApiBuilders` implementing `Category` domain:

[source,java]
----
public class CategoryApiBuilder {

    private final RestClient restClient;

    public CategoryApiBuilder(RestClient restClient) {
        this(restClient);
    }

    public CategorySetApiBuilder categories() {
        return new CategorySetApiBuilder(restClient);
    }

    public CategorySetApiBuilder categories(CategorySetSelector selector) {
        return new CategorySetApiBuilder(restClient, selector);
    }

    public CategoryElementApiBuilder category(Long id) {
        return new CategoryElementApiBuilder(restClient, id);
    }

    public CategoryCreationApiBuilder category(CategoryData data) {
        return new CategoryCreationApiBuilder(restClient, data);
    }
}
----

`CategorySetApiBuilder` implements a complex example of a `API Builder` supporting parameters, allowing filtering the result set, and a configurable operation with additional intermediate methods:

[source,java]
----
public class CategorySetApiBuilder
{
    private final RestClient restClient;
    // Selector parameter received from Client that will be passed to downstream operations
    private final CategorySetSelector selector;

    public CategorySetApiBuilder(RestClient restClient) {
        this(restClient, null);
    }

    public CategorySetApiBuilder(RestClient restClient, CategorySetSelector selector) {
        this.restClient = restClient;
        this.selector = selector;
    }

    /* Selects the domain operation to execute
     */
    public CategoryListOperation list() {
        return new CategoryListOperation(restClient, validator, selector);
    }
}
----

[source,java]
----
public class CategoryListOperation
{
    public static final String ENDPOINT_PATH = "/api/category";

    private final RestClient restClient;
    private final CategorySetSelector selector;
    private Integer pageNumber;
    private Integer pageSize;

    CategoryListOperation(RestClient restClient, CategorySetSelector selector)
    {
        this.restClient = restClient;
        this.selector = selector;
    }

    /* Intermediate operation that allows specifying
     * additional parameters to the request
     */
    public CategoryListOperation paginate(int pageNumber, int pageSize)
    {
        this.pageNumber = pageNumber;
        this.pageSize = pageSize;
        return this;
    }

    /* Method that executes the operation sending the request to the remote service
     */
    public PaginatedResponse<Category> get()
    {
        return restClient.get()
                .uri(this::buildURI)
                .retrieve()
                .body(new ParameterizedTypeReference<PaginatedResponse<Category>>(){});
    }

    private URI buildURI(UriBuilder uriBuilder) {
        uriBuilder.path(ENDPOINT_PATH);
        if(selector != null) {
            uriBuilder.queryParam("selector", URLEncoder.encode(selector.toString(), StandardCharsets.UTF_8));
        }
        if(pageNumber!=null) {
            uriBuilder.queryParam("page", pageNumber);
        }
        if(pageSize!=null) {
            uriBuilder.queryParam("pageSize", pageSize);
        }

        return uriBuilder.build();
    }
}
----

`CategoryElementApiBuilder` is an example of how we can implement multiple operations, with the possibility to bypass the operation, and subdomain `API Builder`s

[source,java]
----
public class CategoryElementApiBuilder {
    private final RestClient restClient;
    private final Long id;

    public CategoryElementApiBuilder(RestClient restClient, Long id) {
        this.restClient = restClient;
        this.id = id;
    }

    /* Bypass operation and execute the operation directly, as this
     * operation is not configurable and doesn't provide additional methods
     */
    public Optional<Category> get() {
        return new CategoryGetOperation(restClient, id).get();
    }

    public Category update(CategoryData data) {
        return new CategoryUpdateOperation(restClient, id, data)
                .update();
    }

    public void delete() {
        return new CategoryDeleteOperation(restClient, id)
                .delete();
    }

    /* Provide access to "product" subdomain API Builder. Parameters
     * received by this API Builder are propagated to the downstream API Builder
     */
    public ProductSetApiBuilder products() {
        return new ProductSetApiBuilder(restClient, id);
    }
}

----

Bypassed `Operation` classes only have a method to execute the request on remote service API.

[source,java]
----
public class CategoryGetOperation {
    public static final String ENDPOINT_PATH = "/api/category/{id}";

    private final RestClient restClient;
    private final Long id;

    CategoryGetOperation(RestClient restClient, Long id) {
        this.restClient = restClient;
        this.id = id;
    }

    public Optional<Category> get()
    {
    	return Optional.ofNullable(
            restClient.get()
                .uri(this::buildURI)
                .retrieve()
                .body(Category.class)
        );
    }

    private URI buildURI(UriBuilder uriBuilder) {
        uriBuilder.path(ENDPOINT_PATH);
        return uriBuilder.build(id);
    }
}
----

[source,java]
----
public class CategoryUpdateOperation {
    public static final String ENDPOINT_PATH = "/api/category/{id}";

    private final RestClient restClient;
    private final Long id;
    private final CategoryData data;

    CategoryUpdateOperation(RestClient restClient, Long id, CategoryData data) {
        this.restClient = restClient;
        this.id = id;
        this.data = data;
    }

    public Category update()
    {
        return restClient.put()
                .uri(this::buildURI)
                .body(data)
                .retrieve()
                .body(Category.class);
    }

    private URI buildURI(UriBuilder uriBuilder) {
        uriBuilder.path(ENDPOINT_PATH);
        return uriBuilder.build(id);
    }
}
----

[source,java]
----
public class CategoryDeleteOperation
{
    public static final String ENDPOINT_PATH = "/api/category/{id}";

    private final RestClient restClient;
    private final Long id;

    CategoryDeleteOperation(RestClient restClient, Long id)
    {
        this.restClient = restClient;
        this.id = id;
    }

    public void delete()
    {
        return restClient.delete()
                .uri(this::buildURI)
                .retrieve()
                .toBodilessEntity();
    }

    private URI buildURI(UriBuilder uriBuilder) {
        uriBuilder.path(ENDPOINT_PATH);
        return uriBuilder.build(id);
    }
}
----

Here we have the subdomain `API Builder` that is called from the main domain `API Builder`. It receives the needed parameters from it and configure `Operation`s according to them.

[source,java]
----
public class ProductSetApiBuilder {
    private final RestClient restClient;
    private final Long categoryId;

    public ProductSetApiBuilder(RestClient restClient, Long categoryId) {
        this.restClient = restClient;
        this.categoryId = categoryId;
    }

    public PaginatedResponse<Product> list() {
        return new ProductListOperation(restClient, categoryId).get();
    }
}
----

[source,java]
----
public class ProductListOperation
{
    public static final String ENDPOINT_PATH = "/api/category/{categoryId}/product";

    private final RestClient restClient;
    private final Long categoryId;

    ProductListOperation(RestClient restClient, Long categoryId)
    {
        this.restClient = restClient;
        this.categoryId = categoryId;
    }

    public PaginatedResponse<Product> get()
    {
        return restClient.get()
                .uri(this::buildURI)
                .retrieve()
                .body(new ParameterizedTypeReference<PaginatedResponse<Product>>(){});
    }

    private URI buildURI(UriBuilder uriBuilder) {
        uriBuilder.path(ENDPOINT_PATH);
        return uriBuilder.build(categoryId);
    }
}
----

`CategoryCreationApiBuilder` is another example of a `API Builder` bypassing operations, as the required data is obtained at the top level client call

[source,java]
----
public class CategoryCreationApiBuilder {
    private final RestClient restClient;
    private final CategoryData data;

    public CategoryCreationApiBuilder(RestClient restClient, CategoryData data)
    {
        this.restClient = restClient;
        this.data = data;
    }

    public Category create()
    {
        return new CategoryCreateOperation(restClient, data)
                .create();
    }
}

----

[source,java]
----
public class CategoryCreateOperation {
    public static final String ENDPOINT_PATH = "/api/category";

    private final RestClient restClient;
    private final CategoryData data;

    CategoryCreateOperation(RestClient restClient, CategoryData data) {
        this.restClient = restClient;
        this.data = data;
    }

    public Category create()
    {
        return restClient.post()
                .uri(this::buildURI)
                .body(data)
                .retrieve()
                .body(Category.class);
    }

    private URI buildURI(UriBuilder uriBuilder) {
        uriBuilder.path(ENDPOINT_PATH);
        return uriBuilder.build();
    }
}
----

Some usage examples:

[source,java]
----

// Category list
PaginatedResponse<Category> response = client.categoryApi()
        .categories()
		.list()
		.paginate(0, 10)
		.get();

// Product list
PaginatedResponse<Product> response = client.categoryApi()
        .category(1001L)
		.products()
		.list();

CategoryData categoryData = buildCategoryData();
// Category creation
Category response = client.categoryApi()
        .category(categoryData)
		.create();

// Category update
Category response = client.categoryApi()
        .category(1001L)
		.update(categoryData);
----
