= Actuators
:toc:

== Configuration
Actuator endpoints must be enabled in `application.properties` exposing only necessary endpoints.

[source,properties]
----
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=info,metrics,health
----

In addition, every endpoint should be enabled individually (See sections below for more details)

Enabled endpoints can be accessed through `/actuator` by default. This can be changed using the `base-path` configuration
in `application.properties`:

[source,properties]
----
management.endpoints.web.base-path: /public/actuator
----

== Endpoints

=== Info

This endpoint allows display information about the application through `/actuator/info` endpoint including
build information generated by `spring-boot-maven-plugin` Maven plugin and random information included in `application.properties`.

First of all, we need to enable the endpoint in `application.properties`

[source,properties]
----
management.endpoint.info.enabled=true
----

To provide build information is necessary to configure `spring-boot-maven-plugin` executing the `build-info` goal.

[source,xml]
----
<plugin>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-maven-plugin</artifactId>
    <!-- . . . -->
    <executions>
        <execution>
            <id>build-info</id>
            <goals>
                <goal>build-info</goal>
            </goals>
        </execution>
        <!-- . . . -->
    </executions>
</plugin>
----

This will generate `build-info.properties` file inside `/target/META-INF` folder with this info. E.G.

[source,properties]
----
build.artifact=springboot-showcase-main
build.group=com.bitsmi.springboot-showcase
build.name=springboot-showcase-main
build.time=2024-03-16T08\:32\:12.088Z
build.version=2.0.0-SNAPSHOT
----

Custom information can be added in `application.properties` enabling `management.info.env.enabled` property
and specifying them using `info` prefix. If properties file is filtered by Maven, we can use Maven env variables
like `project.name`, `project.version`, etc. to make this configuration more general.

[source,properties]
----
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.description=${project.description}
info.app.version=${project.version}
----

We can use an infix to categorize the properties (`app` in the example above), so that endpoint's response will contain inner json objects
according to them.

After doing these configurations, `/actuator/info` will provide us with a response like this:

[source,json]
----
{
  "app": {
    "name": "springboot-showcase-main",
    "description": "SpringBoot Showcase Main",
    "version": "1.0.0-SNAPSHOT"
  },
  "build": {
    "artifact": "springboot-showcase-main",
    "name": "springboot-showcase-main",
    "time": "2024-03-16T08:32:12.088Z",
    "version": "2.0.0-SNAPSHOT",
    "group": "com.bitsmi.springboot-showcase"
  }
}
----

=== Health
This endpoint allows display information about application's health through `/actuator/health` endpoint, including built-in and custom health indicators.

First of all, we need to enable the endpoint in `application.properties`

[source,properties]
----
management.endpoint.health.enabled=true
----

And configure the visibility of the endpoint:

[source,proerties]
----
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
----

The properties above can be configured with one of the following values:

* **never**
* **when-authorized**: Only visible for authorized roles configured in `management.endpoint.health.roles` property
* **always**: Visible for all users. We can use this value also if we want to manage the access to these endpoints directly in Spring-security configuration. E.G.
[source,properties]
----
private void authorizeHttpRequestsBasic(AuthorizeHttpRequestsConfigurer<HttpSecurity>.AuthorizationManagerRequestMatcherRegistry configurer)
{
    configurer
        .requestMatchers(HttpMethod.GET, "/actuator/**").hasAnyRole(UserConstants.USER_GROUP_ADMIN, UserConstants.USER_GROUP_MONITORING)
        .anyRequest().authenticated();
}
----

==== Built-in health indicators

Spring Boot auto-configures the `HealthIndicators` listed in the following table (if module is in classpath and auto-configuration is enabled).
You can also enable or disable selected indicators by configuring `management.health.key.enabled`, with the key listed in the following table:

[cols="keyword,sample,jpql_snippet"]
|===
| Key | Name | Description

| cassandra | CassandraDriverHealthIndicator | Checks that a Cassandra database is up.
| couchbase | CouchbaseHealthIndicator | Checks that a Couchbase cluster is up.
| db | DataSourceHealthIndicator | Checks that a connection to DataSource can be obtained.
| diskspace | DiskSpaceHealthIndicator | Checks for low disk space.
| elasticsearch | ElasticsearchRestClientHealthIndicator | Checks that an Elasticsearch cluster is up.
| hazelcast | HazelcastHealthIndicator | Checks that a Hazelcast server is up.
| influxdb | InfluxDbHealthIndicator | Checks that an InfluxDB server is up.
| jms | JmsHealthIndicator | Checks that a JMS broker is up.
| ldap | LdapHealthIndicator | Checks that an LDAP server is up.
| mail | MailHealthIndicator | Checks that a mail server is up.
| mongo | MongoHealthIndicator | Checks that a Mongo database is up.
| neo4j | Neo4jHealthIndicator | Checks that a Neo4j database is up.
| ping | PingHealthIndicator | Always responds with UP.
| rabbit | RabbitHealthIndicator | Checks that a Rabbit server is up.
| redis | RedisHealthIndicator | Checks that a Redis server is up.
|===

Additional `HealthIndicators` are available but are not enabled by default:

[cols="keyword,sample,jpql_snippet"]
|===
| Key | Name | Description

| livenessstate | LivenessStateHealthIndicator | Exposes the “Liveness” application availability state.
| readinessstate | ReadinessStateHealthIndicator | Exposes the “Readiness” application availability state.
|===

==== Custom health indicators

We can create additional custom health indicators implementing `org.springframework.boot.actuate.health.HealthIndicator` interface or extending `org.springframework.boot.actuate.health.AbstractHealthIndicator` class. For example, if we want to create a Kafka indicator that tell us if the Kafka Broker is UP or DOWN, we can implement as this:

[source,java]
----
@Component
@ConditionalOnEnabledHealthIndicator("kafka")
public class KafkaHealthIndicator extends AbstractHealthIndicator
{
    private final AdminClient kafkaAdminClient;

    public KafkaHealthIndicator(KafkaAdmin kafkaAdmin)
    {
        this.kafkaAdminClient = AdminClient.create(kafkaAdmin.getConfigurationProperties());
    }

    @Override
    protected void doHealthCheck(Builder builder) throws Exception
    {
        final DescribeClusterOptions options = new DescribeClusterOptions().timeoutMs(1000);

        DescribeClusterResult clusterDescription = kafkaAdminClient.describeCluster(options);

        // When Kafka is not connected future.get() throws an exception which in turn sets the indicator DOWN.
        clusterDescription.clusterId().get();

        builder.up().build();

        // Alternatively directly use data from future in health detail.
        builder.up()
                .withDetail("clusterId", clusterDescription.clusterId().get())
                .withDetail("nodeCount", clusterDescription.nodes().get().size())
                .build();
    }
}
----

If we extend the `AbstractHealthIndicator` class this will allow us to include additional information through the provided builder. In the example, the `clusterId` and the `nodeCount` fields.

The name of the indicator class should follow the convention `<Indicator name>HealthIndicator` so Spring will know the indicator name related to the configuration properties related to it.

To allow to enable / disable a custom indicator through it's corresponding configuration property, we must include the `@ConditionalOnEnabledHealthIndicator` annotation specifying the indicator name to it.

==== Indicator groups

Health indicators can be grouped creating a property in `application.properties` with the following format `management.endpoint.health.group.<group name>.include`. E.G. Create a group named `infrastructure` with only `db` and `kafka` indicators.

[source,properties]
----
management.endpoint.health.group.infrastructure.include=db,kafka
----

Doing this we can get the full list of indicators through `/actuators/health` endpoint and only the ones tagged as `infrastruture` using the `/actuators/health/infrastructure` endpoint.

==== Enabling indicators

Indicators can be configured to display information or not in `/actuators/health`. This can be achieved setting `true` or `false` in the corresponding `management.health.<indicator name>.enabled` property. Default indicators can be all enabled / disabled at once using the `management.health.defaults.enabled`.

[source,properties]
----
# Only expose DB and ping components (only applies to default indicators)
management.health.defaults.enabled=false
management.health.db.enabled=true
management.health.ping.enabled=true
# Custom
management.health.kafka.enabled=true
----

WARNING: If an indicator is disabled, remove it from groups, otherwise it will raise an error and application won't start.

=== Metrics
TODO

- `/actuator/metrics`
- `/actuator/metrics/userApiController`
- `/actuator/metrics/userApiController?tag=error%3AIllegalStateException`

=== Custom actuators
TODO

== References
- https://docs.spring.io/spring-boot/docs/3.2.x/actuator-api/htmlsingle/#overview[Actuator overview]
- https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.health[Health reference]
