= Dependency injection

== Features

* xref:multiple-optional-beans[Multiple beans of the same type]
* xref:multiple-optional-beans[Optional beans]
* xref:prototype-scoped-beans[Prototype scoped beans injection]
* xref:prototype-scoped-beans[Parameterized prototype bean factories]
* xref:multiple-optional-beans[Profile dependant beans]
* xref:multiple-optional-beans[Use Spring profiles in tests]
* Test soft assertions using **AssertJ** library

== Relevant code in this example

[NOTE]
====
In order to be less verbose, the package common part is omitted when a class name is specified (`com.bitsmi.springbootshowcase.springcore.dependencyinjection`).

E.G:

`product.service.ProductService` corresponds to `com.bitsmi.springbootshowcase.springcore.dependencyinjection.product.service.ProductService`
====

[id=multiple-optional-beans]
=== Multiple & Optional beans

* `product.service.ProductService`
+
Interface shared by the multiple implementation beans

* `product.service.impl.MainProductServiceImpl`
+
Primary bean implementation that will be autowired in single injections points when no `@Qualifier`
is specified

* `product.service.impl.AdditionalProductServiceImpl` & `product.service.impl.AlternativeProductServiceImpl`
+
Qualified bean implementations. They can be selected individually for injection using their `@Qualifier`

* `product.service.impl.OptionalProfileProductServiceImpl`
+
Bean attached to a profile. It will be only available when the specified profile is active

[id=product-services-int-tests]
* `test.product.service.ProductServicesIntTests` (Integration test)
+
Shows how to autowire beans using:

** Multiple injection point of all bean candidates for a specific type using Java's `Collection`
** `@Autowired(required = false)` annotation for optional single injection point
** Optional single injection point using `ObjectProvider`
** Optional single injection point using Java's `Optional`
** Injection of a `@Primary` bean when multiple beans for the same type are present
** Injection of qualified beans when multiple beans for the same type are present

* `test.product.service.impl.ProfileServicesOptionalProfileIntTests` (Integration test)
+
Similar to xref:product-services-int-tests[ProductServicesIntTests] but including the definition of a **Spring profile** that enables an additional bean (`service.impl.OptionalProfileProductServiceImpl`)

[id=prototype-scoped-beans]
=== Prototype scoped beans

* `scoped.service.PrototypeService`
+
Simple interface to designate a type to retrieve `SimplePrototypeServiceImpl` instances from **Spring Context**

* `scoped.service.ParameterizedService`
+
Simple interface to designate a type to retrieve `ParameterizedServiceImpl` instances from **Spring Context**

* `scoped.service.impl.SimplePrototypeServiceImpl`
+
Simple implementation for a **prototype scoped service**. The main point in this is class is the usage
of `@Scope(BeanDefinition.SCOPE_PROTOTYPE)` along with `@Service` to include the bean in this scope

* `scoped.service.impl.ParameterizedServiceImpl`
+
Parameterized service implementation that receives parameters at construction time.
It will be used to demonstrate how to produce parameterized prototype beans at runtime.
+
It has no `@Service` annotation as its instance as a bean is done through a `ObjectProvider` / xref:parameterized-service-prototype-factory[Factory].

[id=parameterized-service-prototype-factory]
* `scoped.service.ParameterizedServicePrototypeFactory`
+
Example of usage of `@Configuration` annotation to create a **Factory** that allow us to retrieve
parameterized instances of a **prototype bean** defined in a **bean factory method** annotated with `@Bean` and `@Scope(BeanDefinition.SCOPE_PROTOTYPE)`

* `test.scoped.service.PrototypeServicesIntTests` (Integration test)
+
Shows how to retrieve prototype beans using:

** Direct injection
** The injection of an `ObjectProvider`
** Using `ApplicationContext.getBean()` method
** Through a xref:parameterized-service-prototype-factory[custom factory class]

== Related documentation

* xref:spring-docs:how-to/dependency-injection.adoc[Dependency Injection how-to]
* Spring Testing [ ##TODO## ]
