site:
  title: Springboot-Showcase // Docs
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://documentation.kumo-klstr.duckdns.org
  start_page: project-documentation::index.adoc
content:
  sources:
  - url: ../
    branches: HEAD
    start_path: docs/src/main/antora
asciidoc:
  attributes:
    experimental: true
    doctype: book
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
    kroki-fetch-diagram: true
  extensions:
  - asciidoctor-kroki
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
